### ISSUE TITLE
nonce is generated randomly for every request, why do you think it is a good ioc?

### ISSUE THREAD

**Issue by jimwangzx** [phish-report/IOK#2]

**Comment by bradleyjkemp** [comment]
Hey @jimwangzx, great question!

Although it's randomly generated by the original site, when the site gets cloned this nonce value gets saved and no longer gets updated on every request.

e.g. for this rule https://github.com/phish-report/IOK/blob/7a24a31ca10e6dd3030025ab128a48d80cacdfb3/indicators/shopify-YgjX6.yml#L7-L11

Both these pages contain exactly that exact same nonce:
- https://urlscan.io/result/e31ea208-8211-4d42-bb1e-abf0e169c88c/
- https://urlscan.io/result/b4f5ce61-a104-4d71-8418-a6a72951355b/

Theres ~0% chance of that nonce ever occuring again on a legitimate site, so we can be incredibly confident these are the same kit (or at least based on the same clone)

**Comment by jimwangzx** [comment]
I agree. Thanks for the info
