### ISSUE TITLE
FR: Display matching IOKs in case page

### ISSUE THREAD

**Issue by mimi89999** [phish-report/IOK#24]
Hello,
Do you plan to show matching IOKs in case page (for example under `Current Status`)?

**Comment by bradleyjkemp** [comment]
Yes! The plan is to add support for tags on [phish.report](https://phish.report) and have matching IOKs automatically be added as tags (and in future be able to search and filter by tag)

Does that sound a good solution?

**Comment by bradleyjkemp** [comment]
This is now implemented
