### ISSUE TITLE
FR: Web Builder for indicators 

### ISSUE THREAD

**Issue by actually-akac** [phish-report/IOK#77]
We could have a web builder for quickly creating the YAML file, which would further decrease the barriers of entry and speed up rule creation. Rather than writing the full rule, users could click buttons and write into text boxes to build the rule.🚀

**Comment by actually-akac** [comment]
Done.

**Comment by bradleyjkemp** [comment]
I'm currently looking to build something like this into phish.report, is your web builder open source or publicly available anywhere for inspiration?

I've got an IDE-style experience working for actually editing rules but a wizard to generate the initial rule would be excellent

https://github.com/phish-report/IOK/assets/9093713/67299590-5042-408c-a2c6-2adc3517c90a

**Comment by actually-akac** [comment]
> I'm currently looking to build something like this into phish.report, is your web builder open source or publicly available anywhere for inspiration?

It's not useable for anything, since it's just a GUI that allows you to enter all the values into a form and then have it automatically build the PR and submit it.
